version: "3.8"

services:
  mongo:
    image: mongodb
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=scrape
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
      - ./Docker/Volumes/db:/data/db
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mongo-express
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo-express
    restart: unless-stopped
    ports:
      - "27018:8081"
    depends_on:
      - mongo
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge
