version: "3.8"

services:
  mongo:
    build: ./mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-root}
      - MONGO_INITDB_ROOT_DATABASE=${MONGODB_DATABASE:-information}
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - ./docker/volumes/db:/data/db
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge
